In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
import pyodbc 
conn = pyodbc.connect('Driver={SQL Server};'
                      'Server=(Local);'
                      'Database=LogicUniversity;'
                      'Trusted_Connection=yes;')

cursor = conn.cursor()
cursor.execute('SELECT dbo.Orders.POnumber,DateOrdered,dbo.OrderDetails.ItemCode,dbo.OrderDetails.Quantity FROM dbo.Orders INNER JOIN dbo.OrderDetails on dbo.Orders.POnumber=dbo.OrderDetails.POnumber')

for row in cursor:
    print(row)

(99990001, datetime.datetime(2019, 1, 6, 0, 0), 'C001', 62.0)
(99990001, datetime.datetime(2019, 1, 6, 0, 0), 'E002', 67.0)
(99990001, datetime.datetime(2019, 1, 6, 0, 0), 'E035', 16.0)
(99990001, datetime.datetime(2019, 1, 6, 0, 0), 'F033', 94.0)
(99990001, datetime.datetime(2019, 1, 6, 0, 0), 'P032', 94.0)
(99990002, datetime.datetime(2019, 2, 6, 0, 0), 'C002', 29.0)
(99990002, datetime.datetime(2019, 2, 6, 0, 0), 'E003', 28.0)
(99990002, datetime.datetime(2019, 2, 6, 0, 0), 'E036', 76.0)
(99990002, datetime.datetime(2019, 2, 6, 0, 0), 'F034', 67.0)
(99990002, datetime.datetime(2019, 2, 6, 0, 0), 'P033', 67.0)
(99990003, datetime.datetime(2019, 3, 6, 0, 0), 'C001', 55.0)
(99990003, datetime.datetime(2019, 3, 6, 0, 0), 'C003', 66.0)
(99990003, datetime.datetime(2019, 3, 6, 0, 0), 'E004', 62.0)
(99990003, datetime.datetime(2019, 3, 6, 0, 0), 'F020', 28.0)
(99990003, datetime.datetime(2019, 3, 6, 0, 0), 'F035', 28.0)
(99990003, datetime.datetime(2019, 3, 6, 0, 0), 'P034', 28.0)
(99990004, datetime.datetime(2019, 4, 6, 0, 0), 'C002', 81.0)
(99990004, datetime.datetime(2019, 4, 6, 0, 0), 'C004', 75.0)
(99990004, datetime.datetime(2019, 4, 6, 0, 0), 'E005', 29.0)
(99990004, datetime.datetime(2019, 4, 6, 0, 0), 'F021', 57.0)
(99990004, datetime.datetime(2019, 4, 6, 0, 0), 'H011', 62.0)
(99990004, datetime.datetime(2019, 4, 6, 0, 0), 'P035', 74.0)
(99990005, datetime.datetime(2019, 5, 6, 0, 0), 'C003', 42.0)
(99990005, datetime.datetime(2019, 5, 6, 0, 0), 'C005', 96.0)
(99990005, datetime.datetime(2019, 5, 6, 0, 0), 'E006', 55.0)
(99990005, datetime.datetime(2019, 5, 6, 0, 0), 'F022', 64.0)
(99990005, datetime.datetime(2019, 5, 6, 0, 0), 'H012', 29.0)
(99990005, datetime.datetime(2019, 5, 6, 0, 0), 'P036', 95.0)
(99990006, datetime.datetime(2019, 6, 6, 0, 0), 'C004', 35.0)
(99990006, datetime.datetime(2019, 6, 6, 0, 0), 'C006', 90.0)
(99990006, datetime.datetime(2019, 6, 6, 0, 0), 'E007', 81.0)
(99990006, datetime.datetime(2019, 6, 6, 0, 0), 'F023', 14.0)
(99990006, datetime.datetime(2019, 6, 6, 0, 0), 'H013', 55.0)
(99990006, datetime.datetime(2019, 6, 6, 0, 0), 'P037', 46.0)
(99990007, datetime.datetime(2019, 7, 6, 0, 0), 'C005', 3.0)
(99990007, datetime.datetime(2019, 7, 6, 0, 0), 'E001', 53.0)
(99990007, datetime.datetime(2019, 7, 6, 0, 0), 'E008', 42.0)
(99990007, datetime.datetime(2019, 7, 6, 0, 0), 'F024', 15.0)
(99990007, datetime.datetime(2019, 7, 6, 0, 0), 'H014', 81.0)
(99990007, datetime.datetime(2019, 7, 6, 0, 0), 'P038', 50.0)
(99990008, datetime.datetime(2019, 8, 6, 0, 0), 'C001', 2.0)
(99990008, datetime.datetime(2019, 8, 6, 0, 0), 'E002', 32.0)
(99990008, datetime.datetime(2019, 8, 6, 0, 0), 'E020', 35.0)
(99990008, datetime.datetime(2019, 8, 6, 0, 0), 'F031', 11.0)
(99990008, datetime.datetime(2019, 8, 6, 0, 0), 'H031', 42.0)
(99990008, datetime.datetime(2019, 8, 6, 0, 0), 'P039', 87.0)
(99990009, datetime.datetime(2019, 9, 6, 0, 0), 'C002', 7.0)
(99990009, datetime.datetime(2019, 9, 6, 0, 0), 'E003', 80.0)
(99990009, datetime.datetime(2019, 9, 6, 0, 0), 'E021', 3.0)
(99990009, datetime.datetime(2019, 9, 6, 0, 0), 'F032', 96.0)
(99990009, datetime.datetime(2019, 9, 6, 0, 0), 'H032', 35.0)
(99990009, datetime.datetime(2019, 9, 6, 0, 0), 'P040', 36.0)
(99990010, datetime.datetime(2019, 10, 6, 0, 0), 'C003', 16.0)
(99990010, datetime.datetime(2019, 10, 6, 0, 0), 'E004', 60.0)
(99990010, datetime.datetime(2019, 10, 6, 0, 0), 'E030', 2.0)
(99990010, datetime.datetime(2019, 10, 6, 0, 0), 'F033', 94.0)
(99990010, datetime.datetime(2019, 10, 6, 0, 0), 'H033', 3.0)
(99990010, datetime.datetime(2019, 10, 6, 0, 0), 'P041', 4.0)
(99990011, datetime.datetime(2019, 11, 6, 0, 0), 'C004', 76.0)
(99990011, datetime.datetime(2019, 11, 6, 0, 0), 'E005', 5.0)
(99990011, datetime.datetime(2019, 11, 6, 0, 0), 'E031', 7.0)
(99990011, datetime.datetime(2019, 11, 6, 0, 0), 'F034', 67.0)
(99990011, datetime.datetime(2019, 11, 6, 0, 0), 'P010', 2.0)
(99990011, datetime.datetime(2019, 11, 6, 0, 0), 'P042', 27.0)
(99990012, datetime.datetime(2019, 12, 6, 0, 0), 'C005', 28.0)
(99990012, datetime.datetime(2019, 12, 6, 0, 0), 'E006', 90.0)
(99990012, datetime.datetime(2019, 12, 6, 0, 0), 'E032', 16.0)
(99990012, datetime.datetime(2019, 12, 6, 0, 0), 'F035', 28.0)
(99990012, datetime.datetime(2019, 12, 6, 0, 0), 'P011', 7.0)
(99990012, datetime.datetime(2019, 12, 6, 0, 0), 'P043', 7.0)
(99990031, datetime.datetime(2019, 1, 7, 0, 0), 'C005', 76.0)
(99990031, datetime.datetime(2019, 1, 7, 0, 0), 'F020', 56.0)
(99990031, datetime.datetime(2019, 1, 7, 0, 0), 'H031', 27.0)
(99990031, datetime.datetime(2019, 1, 7, 0, 0), 'P032', 29.0)
(99990032, datetime.datetime(2019, 2, 7, 0, 0), 'C006', 28.0)
(99990032, datetime.datetime(2019, 2, 7, 0, 0), 'F021', 50.0)
(99990032, datetime.datetime(2019, 2, 7, 0, 0), 'H032', 7.0)
(99990032, datetime.datetime(2019, 2, 7, 0, 0), 'P033', 55.0)
(99990033, datetime.datetime(2019, 3, 7, 0, 0), 'E001', 57.0)
(99990033, datetime.datetime(2019, 3, 7, 0, 0), 'F022', 60.0)
(99990033, datetime.datetime(2019, 3, 7, 0, 0), 'H033', 56.0)
(99990033, datetime.datetime(2019, 3, 7, 0, 0), 'P034', 81.0)
(99990034, datetime.datetime(2019, 4, 7, 0, 0), 'E002', 64.0)
(99990034, datetime.datetime(2019, 4, 7, 0, 0), 'F023', 66.0)
(99990034, datetime.datetime(2019, 4, 7, 0, 0), 'P010', 50.0)
(99990034, datetime.datetime(2019, 4, 7, 0, 0), 'P035', 42.0)
(99990035, datetime.datetime(2019, 5, 7, 0, 0), 'E003', 14.0)
(99990035, datetime.datetime(2019, 5, 7, 0, 0), 'F024', 75.0)
(99990035, datetime.datetime(2019, 5, 7, 0, 0), 'P011', 60.0)
(99990035, datetime.datetime(2019, 5, 7, 0, 0), 'P036', 35.0)
(99990036, datetime.datetime(2019, 6, 7, 0, 0), 'E004', 15.0)
(99990036, datetime.datetime(2019, 6, 7, 0, 0), 'F031', 96.0)
(99990036, datetime.datetime(2019, 6, 7, 0, 0), 'P012', 66.0)
(99990036, datetime.datetime(2019, 6, 7, 0, 0), 'P037', 3.0)
(99990037, datetime.datetime(2019, 7, 7, 0, 0), 'E005', 11.0)
(99990037, datetime.datetime(2019, 7, 7, 0, 0), 'F032', 90.0)
(99990037, datetime.datetime(2019, 7, 7, 0, 0), 'P013', 75.0)
(99990037, datetime.datetime(2019, 7, 7, 0, 0), 'P038', 2.0)
(99990038, datetime.datetime(2019, 8, 7, 0, 0), 'E006', 96.0)
(99990038, datetime.datetime(2019, 8, 7, 0, 0), 'F033', 53.0)
(99990038, datetime.datetime(2019, 8, 7, 0, 0), 'P014', 96.0)
(99990038, datetime.datetime(2019, 8, 7, 0, 0), 'P039', 7.0)
(99990039, datetime.datetime(2019, 9, 7, 0, 0), 'E007', 94.0)
(99990039, datetime.datetime(2019, 9, 7, 0, 0), 'F034', 32.0)
(99990039, datetime.datetime(2019, 9, 7, 0, 0), 'P015', 90.0)
(99990039, datetime.datetime(2019, 9, 7, 0, 0), 'P040', 16.0)
(99990040, datetime.datetime(2019, 10, 7, 0, 0), 'E008', 67.0)
(99990040, datetime.datetime(2019, 10, 7, 0, 0), 'F035', 80.0)
(99990040, datetime.datetime(2019, 10, 7, 0, 0), 'P016', 53.0)
(99990040, datetime.datetime(2019, 10, 7, 0, 0), 'P041', 76.0)
(99990041, datetime.datetime(2019, 11, 7, 0, 0), 'E020', 28.0)
(99990041, datetime.datetime(2019, 11, 7, 0, 0), 'H011', 60.0)
(99990041, datetime.datetime(2019, 11, 7, 0, 0), 'P020', 62.0)
(99990041, datetime.datetime(2019, 11, 7, 0, 0), 'P042', 28.0)
(99990042, datetime.datetime(2019, 12, 7, 0, 0), 'E021', 74.0)
(99990042, datetime.datetime(2019, 12, 7, 0, 0), 'H012', 5.0)
(99990042, datetime.datetime(2019, 12, 7, 0, 0), 'P021', 29.0)
(99990042, datetime.datetime(2019, 12, 7, 0, 0), 'P043', 57.0)
(99990062, datetime.datetime(2019, 1, 6, 0, 0), 'C006', 60.0)
(99990062, datetime.datetime(2019, 1, 6, 0, 0), 'H013', 5.0)
(99990062, datetime.datetime(2019, 1, 6, 0, 0), 'P035', 94.0)
(99990062, datetime.datetime(2019, 1, 6, 0, 0), 'S100', 74.0)
(99990063, datetime.datetime(2019, 2, 6, 0, 0), 'E001', 66.0)
(99990063, datetime.datetime(2019, 2, 6, 0, 0), 'H014', 90.0)
(99990063, datetime.datetime(2019, 2, 6, 0, 0), 'P036', 67.0)
(99990063, datetime.datetime(2019, 2, 6, 0, 0), 'S040', 95.0)
(99990064, datetime.datetime(2019, 3, 6, 0, 0), 'E002', 75.0)
(99990064, datetime.datetime(2019, 3, 6, 0, 0), 'H031', 62.0)
(99990064, datetime.datetime(2019, 3, 6, 0, 0), 'P037', 28.0)
(99990064, datetime.datetime(2019, 3, 6, 0, 0), 'S041', 46.0)
(99990065, datetime.datetime(2019, 4, 6, 0, 0), 'E003', 96.0)
(99990065, datetime.datetime(2019, 4, 6, 0, 0), 'H032', 29.0)
(99990065, datetime.datetime(2019, 4, 6, 0, 0), 'P038', 62.0)
(99990065, datetime.datetime(2019, 4, 6, 0, 0), 'S101', 50.0)
(99990066, datetime.datetime(2019, 5, 6, 0, 0), 'E004', 90.0)
(99990066, datetime.datetime(2019, 5, 6, 0, 0), 'H033', 55.0)
(99990066, datetime.datetime(2019, 5, 6, 0, 0), 'P039', 29.0)
(99990066, datetime.datetime(2019, 5, 6, 0, 0), 'S010', 87.0)
(99990067, datetime.datetime(2019, 6, 6, 0, 0), 'E005', 53.0)
(99990067, datetime.datetime(2019, 6, 6, 0, 0), 'P010', 81.0)
(99990067, datetime.datetime(2019, 6, 6, 0, 0), 'P040', 55.0)
(99990067, datetime.datetime(2019, 6, 6, 0, 0), 'S011', 36.0)
(99990068, datetime.datetime(2019, 7, 6, 0, 0), 'E006', 32.0)
(99990068, datetime.datetime(2019, 7, 6, 0, 0), 'P011', 42.0)
(99990068, datetime.datetime(2019, 7, 6, 0, 0), 'P041', 81.0)
(99990068, datetime.datetime(2019, 7, 6, 0, 0), 'S012', 4.0)
(99990069, datetime.datetime(2019, 8, 6, 0, 0), 'E007', 80.0)
(99990069, datetime.datetime(2019, 8, 6, 0, 0), 'P012', 35.0)
(99990069, datetime.datetime(2019, 8, 6, 0, 0), 'P042', 42.0)
(99990069, datetime.datetime(2019, 8, 6, 0, 0), 'S020', 27.0)
(99990070, datetime.datetime(2019, 9, 6, 0, 0), 'E008', 60.0)
(99990070, datetime.datetime(2019, 9, 6, 0, 0), 'P011', 7.0)
(99990070, datetime.datetime(2019, 9, 6, 0, 0), 'P013', 3.0)
(99990070, datetime.datetime(2019, 9, 6, 0, 0), 'P043', 35.0)
(99990071, datetime.datetime(2019, 10, 6, 0, 0), 'E020', 5.0)
(99990071, datetime.datetime(2019, 10, 6, 0, 0), 'P012', 56.0)
(99990071, datetime.datetime(2019, 10, 6, 0, 0), 'P014', 2.0)
(99990071, datetime.datetime(2019, 10, 6, 0, 0), 'P044', 3.0)
(99990072, datetime.datetime(2019, 11, 6, 0, 0), 'C001', 90.0)
(99990072, datetime.datetime(2019, 11, 6, 0, 0), 'P013', 50.0)
(99990072, datetime.datetime(2019, 11, 6, 0, 0), 'P015', 7.0)
(99990072, datetime.datetime(2019, 11, 6, 0, 0), 'P045', 2.0)
(99990073, datetime.datetime(2019, 12, 6, 0, 0), 'C002', 62.0)
(99990073, datetime.datetime(2019, 12, 6, 0, 0), 'P014', 60.0)
(99990073, datetime.datetime(2019, 12, 6, 0, 0), 'P016', 16.0)
(99990073, datetime.datetime(2019, 12, 6, 0, 0), 'P046', 7.0)
(99990092, datetime.datetime(2019, 1, 7, 0, 0), 'E002', 4.0)
(99990092, datetime.datetime(2019, 1, 7, 0, 0), 'E008', 67.0)
(99990092, datetime.datetime(2019, 1, 7, 0, 0), 'E035', 7.0)
(99990092, datetime.datetime(2019, 1, 7, 0, 0), 'P046', 27.0)
(99990093, datetime.datetime(2019, 2, 7, 0, 0), 'E003', 27.0)
(99990093, datetime.datetime(2019, 2, 7, 0, 0), 'E020', 28.0)
(99990093, datetime.datetime(2019, 2, 7, 0, 0), 'E036', 16.0)
(99990093, datetime.datetime(2019, 2, 7, 0, 0), 'R001', 7.0)
(99990094, datetime.datetime(2019, 3, 7, 0, 0), 'E004', 7.0)
(99990094, datetime.datetime(2019, 3, 7, 0, 0), 'E021', 74.0)
(99990094, datetime.datetime(2019, 3, 7, 0, 0), 'F020', 76.0)
(99990094, datetime.datetime(2019, 3, 7, 0, 0), 'R002', 56.0)
(99990095, datetime.datetime(2019, 4, 7, 0, 0), 'E005', 56.0)
(99990095, datetime.datetime(2019, 4, 7, 0, 0), 'E030', 95.0)
(99990095, datetime.datetime(2019, 4, 7, 0, 0), 'F021', 28.0)
(99990095, datetime.datetime(2019, 4, 7, 0, 0), 'S100', 50.0)
(99990096, datetime.datetime(2019, 5, 7, 0, 0), 'E006', 50.0)
(99990096, datetime.datetime(2019, 5, 7, 0, 0), 'E031', 46.0)
(99990096, datetime.datetime(2019, 5, 7, 0, 0), 'F022', 57.0)
(99990096, datetime.datetime(2019, 5, 7, 0, 0), 'S040', 60.0)
(99990097, datetime.datetime(2019, 6, 7, 0, 0), 'C001', 50.0)
(99990097, datetime.datetime(2019, 6, 7, 0, 0), 'E007', 60.0)
(99990097, datetime.datetime(2019, 6, 7, 0, 0), 'F023', 64.0)
(99990097, datetime.datetime(2019, 6, 7, 0, 0), 'S041', 66.0)
(99990098, datetime.datetime(2019, 7, 7, 0, 0), 'C002', 87.0)
(99990098, datetime.datetime(2019, 7, 7, 0, 0), 'E008', 66.0)
(99990098, datetime.datetime(2019, 7, 7, 0, 0), 'F024', 14.0)
(99990098, datetime.datetime(2019, 7, 7, 0, 0), 'S101', 75.0)
(99990099, datetime.datetime(2019, 8, 7, 0, 0), 'C001', 36.0)
(99990099, datetime.datetime(2019, 8, 7, 0, 0), 'E020', 75.0)
(99990099, datetime.datetime(2019, 8, 7, 0, 0), 'F031', 15.0)
(99990099, datetime.datetime(2019, 8, 7, 0, 0), 'S010', 96.0)
(99990100, datetime.datetime(2019, 9, 7, 0, 0), 'C002', 4.0)
(99990100, datetime.datetime(2019, 9, 7, 0, 0), 'E021', 96.0)
(99990100, datetime.datetime(2019, 9, 7, 0, 0), 'F032', 11.0)
(99990100, datetime.datetime(2019, 9, 7, 0, 0), 'S011', 90.0)
(99990101, datetime.datetime(2019, 10, 7, 0, 0), 'C003', 27.0)
(99990101, datetime.datetime(2019, 10, 7, 0, 0), 'E030', 90.0)
(99990101, datetime.datetime(2019, 10, 7, 0, 0), 'F033', 96.0)
(99990101, datetime.datetime(2019, 10, 7, 0, 0), 'S012', 53.0)
(99990102, datetime.datetime(2019, 11, 7, 0, 0), 'C004', 7.0)
(99990102, datetime.datetime(2019, 11, 7, 0, 0), 'E031', 53.0)
(99990102, datetime.datetime(2019, 11, 7, 0, 0), 'F034', 94.0)
(99990102, datetime.datetime(2019, 11, 7, 0, 0), 'S020', 32.0)
(99990103, datetime.datetime(2019, 12, 7, 0, 0), 'C005', 56.0)
(99990103, datetime.datetime(2019, 12, 7, 0, 0), 'E032', 62.0)
(99990103, datetime.datetime(2019, 12, 7, 0, 0), 'F035', 67.0)
(99990103, datetime.datetime(2019, 12, 7, 0, 0), 'S021', 80.0)
(99990123, datetime.datetime(2019, 1, 6, 0, 0), 'H032', 28.0)
(99990123, datetime.datetime(2019, 1, 6, 0, 0), 'P011', 11.0)
(99990123, datetime.datetime(2019, 1, 6, 0, 0), 'P014', 80.0)
(99990124, datetime.datetime(2019, 2, 6, 0, 0), 'H033', 74.0)
(99990124, datetime.datetime(2019, 2, 6, 0, 0), 'P012', 96.0)
(99990124, datetime.datetime(2019, 2, 6, 0, 0), 'P034', 60.0)
(99990125, datetime.datetime(2019, 3, 6, 0, 0), 'P010', 95.0)
(99990125, datetime.datetime(2019, 3, 6, 0, 0), 'P013', 94.0)
(99990125, datetime.datetime(2019, 3, 6, 0, 0), 'P035', 5.0)
(99990126, datetime.datetime(2019, 4, 6, 0, 0), 'P011', 46.0)
(99990126, datetime.datetime(2019, 4, 6, 0, 0), 'P014', 67.0)
(99990126, datetime.datetime(2019, 4, 6, 0, 0), 'P036', 90.0)
(99990127, datetime.datetime(2019, 5, 6, 0, 0), 'P012', 50.0)
(99990127, datetime.datetime(2019, 5, 6, 0, 0), 'P037', 62.0)
(99990127, datetime.datetime(2019, 5, 6, 0, 0), 'P042', 28.0)
(99990128, datetime.datetime(2019, 6, 6, 0, 0), 'P013', 87.0)
(99990128, datetime.datetime(2019, 6, 6, 0, 0), 'P038', 29.0)
(99990128, datetime.datetime(2019, 6, 6, 0, 0), 'P043', 62.0)
(99990129, datetime.datetime(2019, 7, 6, 0, 0), 'P014', 36.0)
(99990129, datetime.datetime(2019, 7, 6, 0, 0), 'P039', 55.0)
(99990129, datetime.datetime(2019, 7, 6, 0, 0), 'P044', 29.0)
(99990130, datetime.datetime(2019, 8, 6, 0, 0), 'P015', 4.0)
(99990130, datetime.datetime(2019, 8, 6, 0, 0), 'P040', 81.0)
(99990130, datetime.datetime(2019, 8, 6, 0, 0), 'P045', 55.0)
(99990131, datetime.datetime(2019, 9, 6, 0, 0), 'P016', 27.0)
(99990131, datetime.datetime(2019, 9, 6, 0, 0), 'P041', 42.0)
(99990131, datetime.datetime(2019, 9, 6, 0, 0), 'P046', 81.0)
(99990132, datetime.datetime(2019, 10, 6, 0, 0), 'P020', 7.0)
(99990132, datetime.datetime(2019, 10, 6, 0, 0), 'P042', 35.0)
(99990132, datetime.datetime(2019, 10, 6, 0, 0), 'R001', 42.0)
(99990133, datetime.datetime(2019, 11, 6, 0, 0), 'P021', 56.0)
(99990133, datetime.datetime(2019, 11, 6, 0, 0), 'P043', 3.0)
(99990133, datetime.datetime(2019, 11, 6, 0, 0), 'R002', 35.0)
(99990134, datetime.datetime(2019, 12, 6, 0, 0), 'C001', 3.0)
(99990134, datetime.datetime(2019, 12, 6, 0, 0), 'P011', 50.0)
(99990134, datetime.datetime(2019, 12, 6, 0, 0), 'P044', 2.0)
(99990153, datetime.datetime(2019, 1, 7, 0, 0), 'E007', 87.0)
(99990153, datetime.datetime(2019, 1, 7, 0, 0), 'S100', 2.0)
(99990153, datetime.datetime(2019, 1, 7, 0, 0), 'T020', 94.0)
(99990154, datetime.datetime(2019, 2, 7, 0, 0), 'E008', 36.0)
(99990154, datetime.datetime(2019, 2, 7, 0, 0), 'S040', 7.0)
(99990154, datetime.datetime(2019, 2, 7, 0, 0), 'T021', 67.0)
(99990155, datetime.datetime(2019, 3, 7, 0, 0), 'E020', 4.0)
(99990155, datetime.datetime(2019, 3, 7, 0, 0), 'S041', 16.0)
(99990155, datetime.datetime(2019, 3, 7, 0, 0), 'T022', 28.0)
(99990156, datetime.datetime(2019, 4, 7, 0, 0), 'E021', 27.0)
(99990156, datetime.datetime(2019, 4, 7, 0, 0), 'S101', 76.0)
(99990156, datetime.datetime(2019, 4, 7, 0, 0), 'T023', 74.0)
(99990157, datetime.datetime(2019, 5, 7, 0, 0), 'E030', 7.0)
(99990157, datetime.datetime(2019, 5, 7, 0, 0), 'S010', 28.0)
(99990157, datetime.datetime(2019, 5, 7, 0, 0), 'T024', 95.0)
(99990158, datetime.datetime(2019, 6, 7, 0, 0), 'E031', 56.0)
(99990158, datetime.datetime(2019, 6, 7, 0, 0), 'S011', 57.0)
(99990158, datetime.datetime(2019, 6, 7, 0, 0), 'T025', 46.0)
(99990159, datetime.datetime(2019, 7, 7, 0, 0), 'E032', 50.0)
(99990159, datetime.datetime(2019, 7, 7, 0, 0), 'S012', 64.0)
(99990159, datetime.datetime(2019, 7, 7, 0, 0), 'T100', 50.0)
(99990160, datetime.datetime(2019, 8, 7, 0, 0), 'E033', 60.0)
(99990160, datetime.datetime(2019, 8, 7, 0, 0), 'P031', 87.0)
(99990160, datetime.datetime(2019, 8, 7, 0, 0), 'S020', 14.0)
(99990161, datetime.datetime(2019, 9, 7, 0, 0), 'E034', 66.0)
(99990161, datetime.datetime(2019, 9, 7, 0, 0), 'P032', 36.0)
(99990161, datetime.datetime(2019, 9, 7, 0, 0), 'S021', 15.0)
(99990162, datetime.datetime(2019, 10, 7, 0, 0), 'E035', 75.0)
(99990162, datetime.datetime(2019, 10, 7, 0, 0), 'P033', 4.0)
(99990162, datetime.datetime(2019, 10, 7, 0, 0), 'S022', 11.0)
(99990163, datetime.datetime(2019, 11, 7, 0, 0), 'E036', 96.0)
(99990163, datetime.datetime(2019, 11, 7, 0, 0), 'P034', 27.0)
(99990163, datetime.datetime(2019, 11, 7, 0, 0), 'S023', 96.0)
(99990164, datetime.datetime(2019, 12, 7, 0, 0), 'F020', 90.0)
(99990164, datetime.datetime(2019, 12, 7, 0, 0), 'P035', 7.0)
(99990164, datetime.datetime(2019, 12, 7, 0, 0), 'T001', 94.0)
(99990184, datetime.datetime(2019, 1, 6, 0, 0), 'C003', 3.0)
(99990184, datetime.datetime(2019, 1, 6, 0, 0), 'E001', 94.0)
(99990184, datetime.datetime(2019, 1, 6, 0, 0), 'P014', 32.0)
(99990185, datetime.datetime(2019, 2, 6, 0, 0), 'C004', 2.0)
(99990185, datetime.datetime(2019, 2, 6, 0, 0), 'E002', 67.0)
(99990185, datetime.datetime(2019, 2, 6, 0, 0), 'P042', 80.0)
(99990186, datetime.datetime(2019, 3, 6, 0, 0), 'C005', 7.0)
(99990186, datetime.datetime(2019, 3, 6, 0, 0), 'E003', 28.0)
(99990186, datetime.datetime(2019, 3, 6, 0, 0), 'P043', 60.0)
(99990187, datetime.datetime(2019, 4, 6, 0, 0), 'C001', 16.0)
(99990187, datetime.datetime(2019, 4, 6, 0, 0), 'E004', 74.0)
(99990187, datetime.datetime(2019, 4, 6, 0, 0), 'P044', 5.0)
(99990188, datetime.datetime(2019, 5, 6, 0, 0), 'C002', 76.0)
(99990188, datetime.datetime(2019, 5, 6, 0, 0), 'E005', 95.0)
(99990188, datetime.datetime(2019, 5, 6, 0, 0), 'P045', 90.0)
(99990189, datetime.datetime(2019, 6, 6, 0, 0), 'C003', 28.0)
(99990189, datetime.datetime(2019, 6, 6, 0, 0), 'E006', 46.0)
(99990189, datetime.datetime(2019, 6, 6, 0, 0), 'P046', 62.0)
(99990190, datetime.datetime(2019, 7, 6, 0, 0), 'C004', 57.0)
(99990190, datetime.datetime(2019, 7, 6, 0, 0), 'E007', 50.0)
(99990190, datetime.datetime(2019, 7, 6, 0, 0), 'R001', 29.0)
(99990191, datetime.datetime(2019, 8, 6, 0, 0), 'C005', 64.0)
(99990191, datetime.datetime(2019, 8, 6, 0, 0), 'E008', 87.0)
(99990191, datetime.datetime(2019, 8, 6, 0, 0), 'R002', 55.0)
(99990192, datetime.datetime(2019, 9, 6, 0, 0), 'C006', 14.0)
(99990192, datetime.datetime(2019, 9, 6, 0, 0), 'E020', 36.0)
(99990192, datetime.datetime(2019, 9, 6, 0, 0), 'S100', 81.0)
(99990193, datetime.datetime(2019, 10, 6, 0, 0), 'E001', 15.0)
(99990193, datetime.datetime(2019, 10, 6, 0, 0), 'E021', 4.0)
(99990193, datetime.datetime(2019, 10, 6, 0, 0), 'S040', 42.0)
(99990194, datetime.datetime(2019, 11, 6, 0, 0), 'C001', 35.0)
(99990194, datetime.datetime(2019, 11, 6, 0, 0), 'E002', 11.0)
(99990194, datetime.datetime(2019, 11, 6, 0, 0), 'E030', 27.0)
(99990195, datetime.datetime(2019, 12, 6, 0, 0), 'C002', 3.0)
(99990195, datetime.datetime(2019, 12, 6, 0, 0), 'E003', 96.0)
(99990195, datetime.datetime(2019, 12, 6, 0, 0), 'E031', 7.0)

In [13]:
SQL_Query = pd.read_sql_query(
'''SELECT dbo.Orders.POnumber,DateOrdered,dbo.OrderDetails.ItemCode,dbo.OrderDetails.Quantity FROM dbo.Orders INNER JOIN dbo.OrderDetails on dbo.Orders.POnumber=dbo.OrderDetails.POnumber''', conn)

In [14]:
df = pd.DataFrame(SQL_Query, columns=['POnumber','DateOrdered','ItemCode','Quantity'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 322 entries, 0 to 321
Data columns (total 4 columns):
POnumber       322 non-null int64
DateOrdered    322 non-null datetime64[ns]
ItemCode       322 non-null object
Quantity       322 non-null float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(1)
memory usage: 10.1+ KB

In [15]:
for x in range(0,df.shape[0]):
    code=df.at[x,'ItemCode']
    init = (ord(code[0])%32)
    df.set_value(x, 'ItemCode', int(str(init)+code[1:]))

C:\Users\A0078\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  after removing the cwd from sys.path.

In [16]:
df.head()

   POnumber DateOrdered ItemCode  Quantity
0  99990001  2019-01-06     3001      62.0
1  99990001  2019-01-06     5002      67.0
2  99990001  2019-01-06     5035      16.0
3  99990001  2019-01-06     6033      94.0
4  99990001  2019-01-06    16032      94.0

In [17]:
#extract only the month
df.DateOrdered = [item.month for item in df.DateOrdered]

In [18]:
df.head()

   POnumber  DateOrdered ItemCode  Quantity
0  99990001            1     3001      62.0
1  99990001            1     5002      67.0
2  99990001            1     5035      16.0
3  99990001            1     6033      94.0
4  99990001            1    16032      94.0

In [19]:
from sklearn import linear_model
from sklearn.model_selection import train_test_split

x = df[['ItemCode','DateOrdered']]
y = df['Quantity'] # This is the same as
#y = df.Sales

# default split ratio is 25% for test set
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state = 1)

In [20]:
x_train.head()

    ItemCode  DateOrdered
39     16038            7
271     5033            8
78      5001            3
201    19011            9
147    16012            8

In [21]:
y_train.head()

39     50.0
271    60.0
78     57.0
201    90.0
147    35.0
Name: Quantity, dtype: float64

In [27]:
# import model
#from sklearn.linear_model import LinearRegression

#instantiate
#linReg = LinearRegression()

# fit out linear model to the train set data
#linReg.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
# import the model from sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# we choose k = 3 here, due to the small number of data we have
# there isn't a k suitable for all. Generally we want to choose a small odd number.
# large k is generally more costy
knn_model = KNeighborsClassifier(n_neighbors = 3) 

knn_model.fit(x_train, y_train) # train our model to the data set we have. The training set is all the data points

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [23]:
#y_hat = linReg.predict(x_test)
y_hat = knn_model.predict(x_test)

In [24]:
from sklearn.metrics import mean_squared_error, r2_score

# the error is large due to the data in our set are large values, we should use r2-score to check
mean_squared_error(y_test, y_hat)

2091.3086419753085

In [25]:
r2_score(y_test, y_hat)

-1.262024801849308

In [27]:
import pickle
#pickle.dump(linReg, open('LogicUniversity_LinReg.pkl', 'wb'))
pickle.dump(knn_model, open('LogicUniversity_KNN.pkl', 'wb'))